---
- hosts: web
  become: yes
  become_user: root
  tasks:
  - name: Install remi repo
    yum:
      name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm 
      state: latest

  - name: Import remi GPG Key
    rpm_key:
      key: http://rpms.remirepo.net/RPM-GPG-KEY-remi
      state: present

  - name: Install PHP and Httpd
    yum:
      name:
        - httpd
        - php
        - php-cli
        - php-fpm
        - php-mysqlnd
        - php-zip
        - php-devel
        - php-gd
        - php-mcrypt
        - php-mbstring 
        - php-curl
        - php-xml
        - php-pear
        - php-bcmath
        - php-json
      state: latest
      enablerepo: remi-php73

  - name: Edit Timezone
    lineinfile:
      path: /etc/php.ini
      regexp: ';date.timezone'
      line: 'date.timezone=Asia/Bangkok'
      backup: yes 

  - name: enableserver create
    template:
      src: 'template/enableserver.conf.j2'
      dest: '/etc/httpd/conf.d/enableserver.conf'

  - name: Create directory wwwroot
    file:
      path: /var/www/{{ item }}
      state: directory
      mode: 0755
    loop:
      - my-site.com/html
      - my-site.com/log
      - mynet-803.com/html
      - mynet-803.com/log

  - name: change mode www
    file:
      path: /var/www
      mode: "0755"

  - name: create web 01 mynet-803.com.conf
    template:
      src: 'template/web-01.mynet-803.com.conf.j2'
      dest: '/etc/httpd/conf.d/web-01.mynet-803.com.conf'
    when: ansible_ssh_host == '192.168.100.81'

  - name: create web 01 my-site.com.conf
    template:
      src: 'template/web-01.my-site.com.conf.j2'
      dest: '/etc/httpd/conf.d/web-01.my-site.com.conf'
    when: ansible_ssh_host == '192.168.100.81'

  - name: create web 02 mynet-803.com.conf
    template:
      src: 'template/web-02.mynet-803.com.conf.j2'
      dest: '/etc/httpd/conf.d/web-02.mynet-803.com.conf'
    when: ansible_ssh_host == '192.168.100.82'

  - name: create web 02 my-site.com.conf
    template:
      src: 'template/web-02.my-site.com.conf.j2'
      dest: '/etc/httpd/conf.d/web-02.my-site.com.conf'
    when: ansible_ssh_host == '192.168.100.82'

  - name: file web 01 index.php
    template:
      src: 'template/index1.php.j2'
      dest: '/var/www/mynet-803.com/html/index.php'
    when: ansible_ssh_host == '192.168.100.81' 
    
  - name: file web 01 index.php
    template:
      src: 'template/index2.php.j2'
      dest: '/var/www/my-site.com/html/index.php'
    when: ansible_ssh_host == '192.168.100.81'

  - name: file web 02 index.php
    template:
      src: 'template/index3.php.j2'
      dest: '/var/www/mynet-803.com/html/index.php'
    when: ansible_ssh_host == '192.168.100.82' 
    
  - name: file web 02 index.php
    template:
      src: 'template/index4.php.j2'
      dest: '/var/www/my-site.com/html/index.php'
    when: ansible_ssh_host == '192.168.100.82'

  - name: Enable httpd
    service:
      name: httpd
      enabled: yes
    
  - name: Start httpd
    service:
      name: httpd
      state: started

  - name: Enable service firewall
    service:
      name: firewalld
      enabled: yes
  
  - name: Start firewall
    service:
      name: firewalld
      state: started

  - name: Open firewall
    firewalld:
      port: '{{ item }}'
      permanent: yes
      state: enabled
    loop:
    - "80/tcp"
    - "443/tcp"
  - name: Restart firewalld
    service:
      name: firewalld
      state: restarted

  - name: Copy index.php
    template:
      src: 'template/index.php.j2'
      dest: '/var/www/html/index.php'
      owner: root
      group: root
      mode: "775"

- hosts: db
  become: yes
  become_user: root
  tasks:
  
  - name: Install maria db
    yum:
      name: mariadb-server
      state: latest

  - name: Enable service maria db
    service:
      name: mariadb
      enabled: yes

  - name: Start service maria db
    service:
      name: mariadb
      state: started

  - name: Enable service firewall
    service:
      name: firewalld
      enabled: yes
  
  - name: Start firewall
    service:
      name: firewalld
      state: started

  - name: Open firewall
    firewalld:
      port: '3306/tcp'
      permanent: yes
      state: enabled

  - name: Restart firewalld
    service:
      name: firewalld
      state: restarted
   

